# Generated by Django 4.0.5 on 2022-07-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_passwordreset_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='status',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
