# Generated by Django 4.0.5 on 2022-07-15 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawtool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 17, 2, 51, 110649)),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 17, 2, 51, 111656)),
        ),
        migrations.AlterField(
            model_name='measure',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
